/**
 * lib/ghl/llms-generator.ts
 * --------------------------
 * Formats discovered funnel/page data into a valid llms.txt file
 * following the specification at https://llmstxt.org
 *
 * Format:
 *   # Site Name
 *   > One-line summary of what the site does
 *
 *   ## Funnel Name
 *   - [Page Name](https://url/path): Optional page description
 */

import type { FunnelWithPages } from "./funnels";

export interface GeneratorOptions {
  siteName: string;
  siteDescription?: string;
  locationId: string;
  /** Base URL for building absolute URLs when page URLs are relative paths */
  baseUrl?: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function resolveUrl(
  path: string | undefined,
  baseUrl: string | undefined
): string {
  if (!path) return "#";
  if (path.startsWith("http")) return path;
  if (baseUrl) return `${baseUrl.replace(/\/$/, "")}/${path.replace(/^\//, "")}`;
  return path;
}

function sanitize(text: string): string {
  return text.replace(/[\r\n]+/g, " ").trim();
}

// ─── Main Generator ───────────────────────────────────────────────────────────

/**
 * Generates a well-formed llms.txt markdown string from funnel/page data.
 */
export function generateLlmsTxt(
  funnels: FunnelWithPages[],
  options: GeneratorOptions
): string {
  const { siteName, siteDescription, baseUrl } = options;

  const lines: string[] = [];

  // H1: Project / Site name
  lines.push(`# ${sanitize(siteName)}`);
  lines.push("");

  // Blockquote: Summary
  const summary =
    siteDescription ??
    `This site contains ${funnels.length} funnel(s) with their associated pages, auto-generated for AI assistant consumption.`;
  lines.push(`> ${sanitize(summary)}`);
  lines.push("");

  // Per-funnel H2 sections
  for (const funnel of funnels) {
    if (funnel.pages.length === 0) continue;

    lines.push(`## ${sanitize(funnel.name)}`);
    lines.push("");

    for (const page of funnel.pages) {
      const url = resolveUrl(
        page.url ?? page.pathName,
        baseUrl ?? funnel.url
      );
      const label = sanitize(page.name);
      lines.push(`- [${label}](${url})`);
    }

    lines.push("");
  }

  // Append generation metadata as a comment for traceability
  lines.push(
    `<!-- Generated by GHL llms.txt Plugin on ${new Date().toISOString()} -->`
  );

  return lines.join("\n");
}

/**
 * Returns the filename to use when uploading to GHL Media.
 * We include a timestamp to avoid CDN/Browser caching issues when re-generating.
 */
export function getLlmsTxtFilename(): string {
  return `llms_${Date.now()}.txt`;
}
