import Link from "next/link";

export const metadata = {
  title: "Terms of Service | GHL llms.txt Plugin",
};

export default function TermsPage() {
  return (
    <main className="landing-root" style={{ justifyContent: "flex-start", paddingTop: "4rem" }}>
      <div className="landing-inner" style={{ textAlign: "left", alignItems: "flex-start", maxWidth: "800px" }}>
        <Link href="/" className="btn btn-secondary" style={{ marginBottom: "2rem" }}>
          ← Back to Home
        </Link>
        
        <h1 className="landing-title" style={{ fontSize: "2.5rem", textAlign: "left", marginBottom: "1rem" }}>
          Terms of <span className="highlight">Service</span>
        </h1>
        
        <div className="landing-desc" style={{ maxWidth: "none", color: "var(--text)" }}>
          <p style={{ marginBottom: "1.5rem" }}>Last Updated: April 25, 2026</p>
          
          <h2 style={{ color: "var(--brand-light)", marginTop: "2rem", marginBottom: "1rem" }}>1. Acceptance of Terms</h2>
          <p style={{ marginBottom: "1.5rem" }}>
            By installing and using the GHL llms.txt Plugin, you agree to be bound by these Terms of Service. 
            If you do not agree, please do not use the application.
          </p>

          <h2 style={{ color: "var(--brand-light)", marginTop: "2rem", marginBottom: "1rem" }}>2. Description of Service</h2>
          <p style={{ marginBottom: "1.5rem" }}>
            The Service provides automation tools for GoHighLevel users to generate and host llms.txt files. 
            We provide the software &quot;as is&quot; and make no guarantees regarding uptime or specific performance outcomes.
          </p>

          <h2 style={{ color: "var(--brand-light)", marginTop: "2rem", marginBottom: "1rem" }}>3. User Obligations</h2>
          <p style={{ marginBottom: "1.5rem" }}>
            You are responsible for ensuring that the content generated by the plugin and hosted on your domain complies with your own local laws and regulations. 
            You must not use the plugin for any illegal or unauthorized purpose.
          </p>

          <h2 style={{ color: "var(--brand-light)", marginTop: "2rem", marginBottom: "1rem" }}>4. Intellectual Property</h2>
          <p style={{ marginBottom: "1.5rem" }}>
            All intellectual property rights in the software and the service are owned by the developers. 
            You are granted a limited, non-exclusive license to use the service through the GoHighLevel marketplace.
          </p>

          <h2 style={{ color: "var(--brand-light)", marginTop: "2rem", marginBottom: "1rem" }}>5. Limitation of Liability</h2>
          <p style={{ marginBottom: "1.5rem" }}>
            We shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service.
          </p>

          <h2 style={{ color: "var(--brand-light)", marginTop: "2rem", marginBottom: "1rem" }}>6. Termination</h2>
          <p style={{ marginBottom: "1.5rem" }}>
            We reserve the right to terminate or suspend access to our service immediately, without prior notice, for any reason whatsoever.
          </p>
        </div>
      </div>
    </main>
  );
}
